import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const read = (path) => readFileSync(path, 'utf8').replaceAll('\r\n', '\n');
export function loadPlan(root = repoRoot) {
  const manifest = JSON.parse(read(join(root, 'supabase/bootstrap/manifest.json')));
  const actual = readdirSync(join(root, 'supabase/migrations')).filter((name) => name.endsWith('.sql')).sort();
  const ordered = manifest.migrations;
  if (manifest.version !== 1 || !Array.isArray(ordered)) throw new Error('Invalid bootstrap manifest');
  if (new Set(ordered).size !== ordered.length) throw new Error('Duplicate migration in bootstrap manifest');
  if (JSON.stringify([...ordered].sort()) !== JSON.stringify(actual)) {
    throw new Error(`Migration inventory differs: missing=${actual.filter((name) => !ordered.includes(name))}; stale=${ordered.filter((name) => !actual.includes(name))}`);
  }
  return [
    { name: 'initial', source: 'supabase/bootstrap/initial.sql', sql: read(join(root, 'supabase/bootstrap/initial.sql')) },
    ...ordered.map((name) => {
      let source = `supabase/migrations/${name}`;
      let sql = read(join(root, source));
      const originalSha256 = createHash('sha256').update(sql).digest('hex');
      // This historical migration consists entirely of data moves for two specific
      // production sagas. A fresh local database must never invent those records.
      if (name === '20260728_migrar_grafos_a_itinerarios.sql') {
        source = 'supabase/bootstrap/empty-graph-data.sql';
        sql = read(join(root, source));
      }
      return { name: name.replace(/\.sql$/, ''), source, sql, originalSha256 };
    }),
  ];
}

export function renderBaseline(root = repoRoot) {
  const steps = loadPlan(root);
  return `-- GENERATED by scripts/db/bootstrap.mjs --baseline. Do not edit by hand.
-- Empty database only. Requires psql (not the SQL editor); stop on the first error.
-- Sources: bootstrap/initial.sql + bootstrap/manifest.json + migrations/*.sql.
\\set ON_ERROR_STOP on
` + steps.map((step) => `\n-- ${step.name}\nbegin;\n\\ir ${step.source.slice('supabase/'.length)}\ncommit;\n`).join('');
}

export function prepare(root = repoRoot, destination = join(root, '.superpowers/supabase-local')) {
  const plan = loadPlan(root);
  const migrationDir = join(destination, 'supabase/migrations');
  // Never silently replace a generated migration history: the caller must use a
  // fresh destination, or reset the same unchanged plan explicitly via Supabase.
  const signature = createHash('sha256').update(JSON.stringify(plan)).digest('hex');
  const stamp = join(destination, 'bootstrap.json');
  if (existsSync(destination) && !existsSync(stamp) && readdirSync(destination).length) {
    throw new Error('Refusing to overwrite a non-bootstrap directory');
  }
  if (existsSync(stamp) && JSON.parse(read(stamp)).signature !== signature) {
    throw new Error('Bootstrap sources changed. Stop/remove the disposable local instance before preparing a fresh directory.');
  }
  const expected = plan.map((step, index) => `${20000101000000n + BigInt(index)}_${step.name}.sql`);
  if (existsSync(migrationDir) && readdirSync(migrationDir).some((file) => !expected.includes(file))) {
    throw new Error('Unexpected file in generated migration directory');
  }
  mkdirSync(migrationDir, { recursive: true });
  const projectId = `biblioshare-local-${createHash('sha256').update(resolve(destination)).digest('hex').slice(0, 8)}`;
  const mapping = plan.map((step, index) => {
    // Ordinal local ledger, independent of historical duplicate/8-digit names.
    const version = String(20000101000000n + BigInt(index));
    const filename = `${version}_${step.name}.sql`;
    writeFileSync(join(migrationDir, filename), `-- Source: ${step.source}\n${step.sql}`);
    return { version, file: filename, source: step.source, sha256: createHash('sha256').update(step.sql).digest('hex'), originalSha256: step.originalSha256 };
  });
  writeFileSync(join(destination, 'supabase/config.toml'), `project_id = "${projectId}"\n
[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.seed]
enabled = false

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["http://localhost:3000/**", "http://127.0.0.1:3000/**"]

[analytics]
enabled = false
`);
  writeFileSync(stamp, JSON.stringify({ signature, projectId, migrations: mapping }, null, 2) + '\n');
  return { destination, projectId, count: plan.length };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    if (process.argv.includes('--baseline')) {
      writeFileSync(join(repoRoot, 'supabase/schema-baseline.sql'), renderBaseline());
      console.log('Generated psql baseline from the complete migration manifest.');
    } else {
      console.log(JSON.stringify(prepare(), null, 2));
    }
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
