-- GENERATED by scripts/db/bootstrap.mjs --baseline. Do not edit by hand.
-- Empty database only. Requires psql (not the SQL editor); stop on the first error.
-- Sources: bootstrap/initial.sql + bootstrap/manifest.json + migrations/*.sql.
\set ON_ERROR_STOP on

-- initial
begin;
\ir bootstrap/initial.sql
commit;

-- 20260710_avatars_storage
begin;
\ir migrations/20260710_avatars_storage.sql
commit;

-- 20260710_challenges
begin;
\ir migrations/20260710_challenges.sql
commit;

-- 20260710_multiple_queues
begin;
\ir migrations/20260710_multiple_queues.sql
commit;

-- 20260710_pending_import_rows
begin;
\ir migrations/20260710_pending_import_rows.sql
commit;

-- 20260710_reorder_queue_into
begin;
\ir migrations/20260710_reorder_queue_into.sql
commit;

-- 20260710_reorder_queue_rpc
begin;
\ir migrations/20260710_reorder_queue_rpc.sql
commit;

-- 20260710_series_episodes
begin;
\ir migrations/20260710_series_episodes.sql
commit;

-- 20260710_typed_annual_goals_and_series_runtime
begin;
\ir migrations/20260710_typed_annual_goals_and_series_runtime.sql
commit;

-- 20260711_social_follows
begin;
\ir migrations/20260711_social_follows.sql
commit;

-- 20260711_notifications
begin;
\ir migrations/20260711_notifications.sql
commit;

-- 20260711_profile_identities
begin;
\ir migrations/20260711_profile_identities.sql
commit;

-- 20260711_review_interactions
begin;
\ir migrations/20260711_review_interactions.sql
commit;

-- 20260712_clubs
begin;
\ir migrations/20260712_clubs.sql
commit;

-- 20260712_club_posts
begin;
\ir migrations/20260712_club_posts.sql
commit;

-- 20260712_notifications_delete_policy
begin;
\ir migrations/20260712_notifications_delete_policy.sql
commit;

-- 20260712_push_subscriptions
begin;
\ir migrations/20260712_push_subscriptions.sql
commit;

-- 20260713_club_activities
begin;
\ir migrations/20260713_club_activities.sql
commit;

-- 20260713_activity_checkpoints
begin;
\ir migrations/20260713_activity_checkpoints.sql
commit;

-- 20260713_checkpoint_due_on
begin;
\ir migrations/20260713_checkpoint_due_on.sql
commit;

-- 20260713_club_posts_share_visibility_fix
begin;
\ir migrations/20260713_club_posts_share_visibility_fix.sql
commit;

-- 20260713_club_stats
begin;
\ir migrations/20260713_club_stats.sql
commit;

-- 20260713_list_challenge
begin;
\ir migrations/20260713_list_challenge.sql
commit;

-- 20260713_profile_identities_revoke_writes
begin;
\ir migrations/20260713_profile_identities_revoke_writes.sql
commit;

-- 20260714_club_requested_enum
begin;
\ir migrations/20260714_club_requested_enum.sql
commit;

-- 20260714_notification_join_request_enum
begin;
\ir migrations/20260714_notification_join_request_enum.sql
commit;

-- 20260714_club_join_requests
begin;
\ir migrations/20260714_club_join_requests.sql
commit;

-- 20260714_club_is_private_helper
begin;
\ir migrations/20260714_club_is_private_helper.sql
commit;

-- 20260714_criteria_challenge
begin;
\ir migrations/20260714_criteria_challenge.sql
commit;

-- 20260714_editions
begin;
\ir migrations/20260714_editions.sql
commit;

-- 20260714_editions_b_primary
begin;
\ir migrations/20260714_editions_b_primary.sql
commit;

-- 20260714_editions_c_register
begin;
\ir migrations/20260714_editions_c_register.sql
commit;

-- 20260714_editions_d_sync
begin;
\ir migrations/20260714_editions_d_sync.sql
commit;

-- 20260714_editions_e_sync_rls
begin;
\ir migrations/20260714_editions_e_sync_rls.sql
commit;

-- 20260714_editions_f_delete_guard
begin;
\ir migrations/20260714_editions_f_delete_guard.sql
commit;

-- 20260714_editions_g_covers_bucket
begin;
\ir migrations/20260714_editions_g_covers_bucket.sql
commit;

-- 20260714_editions_h_catalog_edit_grants
begin;
\ir migrations/20260714_editions_h_catalog_edit_grants.sql
commit;

-- 20260714_passes
begin;
\ir migrations/20260714_passes.sql
commit;

-- 20260714_passes_integrity
begin;
\ir migrations/20260714_passes_integrity.sql
commit;

-- 20260714_passes_d_advisors
begin;
\ir migrations/20260714_passes_d_advisors.sql
commit;

-- 20260714_passes_grants
begin;
\ir migrations/20260714_passes_grants.sql
commit;

-- 20260715_club_share_ownership
begin;
\ir migrations/20260715_club_share_ownership.sql
commit;

-- 20260714_passes_review_privacy
begin;
\ir migrations/20260714_passes_review_privacy.sql
commit;

-- 20260714_tierlist
begin;
\ir migrations/20260714_tierlist.sql
commit;

-- 20260713_propose_with_setup
begin;
\ir migrations/20260713_propose_with_setup.sql
commit;

-- 20260715_book_editions_no_blank_primary
begin;
\ir migrations/20260715_book_editions_no_blank_primary.sql
commit;

-- 20260715_book_hydration
begin;
\ir migrations/20260715_book_hydration.sql
commit;

-- 20260715_book_hydration_revoke_anon
begin;
\ir migrations/20260715_book_hydration_revoke_anon.sql
commit;

-- 20260715_consolidate_activity_items_policies
begin;
\ir migrations/20260715_consolidate_activity_items_policies.sql
commit;

-- 20260715_enrich_only_and_hardening
begin;
\ir migrations/20260715_enrich_only_and_hardening.sql
commit;

-- 20260715_text_length_limits
begin;
\ir migrations/20260715_text_length_limits.sql
commit;

-- 20260716_list_challenge_completion_mode
begin;
\ir migrations/20260716_list_challenge_completion_mode.sql
commit;

-- 20260716_pass_hub_a_columns
begin;
\ir migrations/20260716_pass_hub_a_columns.sql
commit;

-- 20260716_pass_hub_a_view_pinned
begin;
\ir migrations/20260716_pass_hub_a_view_pinned.sql
commit;

-- 20260716_pass_hub_b_satellites
begin;
\ir migrations/20260716_pass_hub_b_satellites.sql
commit;

-- 20260717_pass_hub_b2_episode_unique
begin;
\ir migrations/20260717_pass_hub_b2_episode_unique.sql
commit;

-- 20260717_pass_hub_b3_fk_set_null
begin;
\ir migrations/20260717_pass_hub_b3_fk_set_null.sql
commit;

-- 20260717_pass_hub_b4_hub_writes
begin;
\ir migrations/20260717_pass_hub_b4_hub_writes.sql
commit;

-- 20260717_pass_hub_b5_sessions_optional
begin;
\ir migrations/20260717_pass_hub_b5_sessions_optional.sql
commit;

-- 20260717_pass_hub_c_rename
begin;
\ir migrations/20260717_pass_hub_c_rename.sql
commit;

-- 20260717_notes
begin;
\ir migrations/20260717_notes.sql
commit;

-- 20260717_fuse_annual_goals_into_challenges
begin;
\ir migrations/20260717_fuse_annual_goals_into_challenges.sql
commit;

-- 20260717_progress_sessions_started_at
begin;
\ir migrations/20260717_progress_sessions_started_at.sql
commit;

-- 20260718_activity_chat_target
begin;
\ir migrations/20260718_activity_chat_target.sql
commit;

-- 20260718_activity_interconnection
begin;
\ir migrations/20260718_activity_interconnection.sql
commit;

-- 20260718_activity_interconnection_fix
begin;
\ir migrations/20260718_activity_interconnection_fix.sql
commit;

-- 20260718_collections
begin;
\ir migrations/20260718_collections.sql
commit;

-- 20260718_spawned_tierlist_default_tiers
begin;
\ir migrations/20260718_spawned_tierlist_default_tiers.sql
commit;

-- 20260719_promote_active_pass_after_delete
begin;
\ir migrations/20260719_promote_active_pass_after_delete.sql
commit;

-- 20260719_saga_follows
begin;
\ir migrations/20260719_saga_follows.sql
commit;

-- 20260719_sagas_hierarchy
begin;
\ir migrations/20260719_sagas_hierarchy.sql
commit;

-- 20260719_saga_graph
begin;
\ir migrations/20260719_saga_graph.sql
commit;

-- 20260719_saga_items_update_policy
begin;
\ir migrations/20260719_saga_items_update_policy.sql
commit;

-- 20260719_saga_multi_membership
begin;
\ir migrations/20260719_saga_multi_membership.sql
commit;

-- 20260719_sagas_delete_policy
begin;
\ir migrations/20260719_sagas_delete_policy.sql
commit;

-- 20260719_sagas_insert_hardening
begin;
\ir migrations/20260719_sagas_insert_hardening.sql
commit;

-- 20260719_save_saga_graph_rpc
begin;
\ir migrations/20260719_save_saga_graph_rpc.sql
commit;

-- 20260720_collections_sorteable
begin;
\ir migrations/20260720_collections_sorteable.sql
commit;

-- 20260720_drop_queues
begin;
\ir migrations/20260720_drop_queues.sql
commit;

-- 20260720_onboarding
begin;
\ir migrations/20260720_onboarding.sql
commit;

-- 20260721_notes_social_columns
begin;
\ir migrations/20260721_notes_social_columns.sql
commit;

-- 20260722_activity_kind_evento
begin;
\ir migrations/20260722_activity_kind_evento.sql
commit;

-- 20260722_club_event_rpcs
begin;
\ir migrations/20260722_club_event_rpcs.sql
commit;

-- 20260722_saga_items_rls_hardening
begin;
\ir migrations/20260722_saga_items_rls_hardening.sql
commit;

-- 20260723_saga_item_role
begin;
\ir migrations/20260723_saga_item_role.sql
commit;

-- 20260723_saga_routes
begin;
\ir migrations/20260723_saga_routes.sql
commit;

-- 20260723_saga_route_entries_uniques
begin;
\ir migrations/20260723_saga_route_entries_uniques.sql
commit;

-- 20260725_saga_placement
begin;
\ir migrations/20260725_saga_placement.sql
commit;

-- 20260725_saga_placement_blocks
begin;
\ir migrations/20260725_saga_placement_blocks.sql
commit;

-- 20260726_rescate_colocacion_hijas
begin;
\ir migrations/20260726_rescate_colocacion_hijas.sql
commit;

-- 20260726_saga_items_placement_writers_fix
begin;
\ir migrations/20260726_saga_items_placement_writers_fix.sql
commit;

-- 20260726_save_saga_sequence
begin;
\ir migrations/20260726_save_saga_sequence.sql
commit;

-- 20260727_saga_placement_windows
begin;
\ir migrations/20260727_saga_placement_windows.sql
commit;

-- 20260727_save_saga_sequence_windows
begin;
\ir migrations/20260727_save_saga_sequence_windows.sql
commit;

-- 20260728_drop_save_saga_sequence_v4
begin;
\ir migrations/20260728_drop_save_saga_sequence_v4.sql
commit;

-- 20260728_migrar_grafos_a_itinerarios
begin;
\ir bootstrap/empty-graph-data.sql
commit;

-- 20260728_sagas_show_map
begin;
\ir migrations/20260728_sagas_show_map.sql
commit;

-- 20260729_drop_saga_graph
begin;
\ir migrations/20260729_drop_saga_graph.sql
commit;

-- 20260730_saga_routes_is_reading_order
begin;
\ir migrations/20260730_saga_routes_is_reading_order.sql
commit;

-- 20260730_save_saga_sequence_subjects
begin;
\ir migrations/20260730_save_saga_sequence_subjects.sql
commit;

-- 20260812_feed_targets_enum
begin;
\ir migrations/20260812_feed_targets_enum.sql
commit;

-- 20260813_feed_targets_can_view
begin;
\ir migrations/20260813_feed_targets_can_view.sql
commit;

-- 20260730190602_social_phase0_integrity
begin;
\ir migrations/20260730190602_social_phase0_integrity.sql
commit;

-- 20260730190801_social_phase0_notification_compat
begin;
\ir migrations/20260730190801_social_phase0_notification_compat.sql
commit;

-- 20260730191652_social_phase0_user_blocks
begin;
\ir migrations/20260730191652_social_phase0_user_blocks.sql
commit;

-- 20260730191702_social_phase0_moderation_reports
begin;
\ir migrations/20260730191702_social_phase0_moderation_reports.sql
commit;

-- 20260730191708_social_phase0_polymorphic_cleanup
begin;
\ir migrations/20260730191708_social_phase0_polymorphic_cleanup.sql
commit;

-- 20260730194407_social_phase0_close_notification_inserts
begin;
\ir migrations/20260730194407_social_phase0_close_notification_inserts.sql
commit;

-- 20260730200000_social_phase0_report_reviewer_index
begin;
\ir migrations/20260730200000_social_phase0_report_reviewer_index.sql
commit;

-- 20260730212803_social_interaction_targets_expand
begin;
\ir migrations/20260730212803_social_interaction_targets_expand.sql
commit;

-- 20260730213248_social_interaction_targets_security
begin;
\ir migrations/20260730213248_social_interaction_targets_security.sql
commit;

-- 20260730214405_social_interaction_targets_compatibility_hardening
begin;
\ir migrations/20260730214405_social_interaction_targets_compatibility_hardening.sql
commit;

-- 20260730214621_social_interaction_targets_visibility_acl
begin;
\ir migrations/20260730214621_social_interaction_targets_visibility_acl.sql
commit;

-- 20260731_drop_save_saga_sequence_v5
begin;
\ir migrations/20260731_drop_save_saga_sequence_v5.sql
commit;

-- 20260801_saga_tandems
begin;
\ir migrations/20260801_saga_tandems.sql
commit;

-- 20260801_save_saga_sequence_tandems
begin;
\ir migrations/20260801_save_saga_sequence_tandems.sql
commit;

-- 20260801115944_social_interaction_targets_checkpoint_owner_fix
begin;
\ir migrations/20260801115944_social_interaction_targets_checkpoint_owner_fix.sql
commit;

-- 20260801135656_social_interaction_targets_notification_writer_fix
begin;
\ir migrations/20260801135656_social_interaction_targets_notification_writer_fix.sql
commit;

-- 20260802_drop_save_saga_sequence_v6
begin;
\ir migrations/20260802_drop_save_saga_sequence_v6.sql
commit;

-- 20260802_screen_original_title
begin;
\ir migrations/20260802_screen_original_title.sql
commit;

-- 20260802013421_social_interaction_targets_checkpoint_audience_fix
begin;
\ir migrations/20260802013421_social_interaction_targets_checkpoint_audience_fix.sql
commit;

-- 20260801224621_social_interaction_targets_contract
begin;
\ir migrations/20260801224621_social_interaction_targets_contract.sql
commit;

-- 20260803_club_rounds
begin;
\ir migrations/20260803_club_rounds.sql
commit;

-- 20260803_saga_window_reason
begin;
\ir migrations/20260803_saga_window_reason.sql
commit;

-- 20260804_save_saga_sequence_motivo
begin;
\ir migrations/20260804_save_saga_sequence_motivo.sql
commit;

-- 20260804000000_follow_notify_events
begin;
\ir migrations/20260804000000_follow_notify_events.sql
commit;

-- 20260804000001_notification_type_followed
begin;
\ir migrations/20260804000001_notification_type_followed.sql
commit;

-- 20260805_saga_optional_skips
begin;
\ir migrations/20260805_saga_optional_skips.sql
commit;

-- 20260805_user_celebrations
begin;
\ir migrations/20260805_user_celebrations.sql
commit;

-- 20260806_get_widget_snapshot
begin;
\ir migrations/20260806_get_widget_snapshot.sql
commit;

-- 20260806_saga_item_role_ampliado
begin;
\ir migrations/20260806_saga_item_role_ampliado.sql
commit;

-- 20260806_widget_snapshot_edition_pages
begin;
\ir migrations/20260806_widget_snapshot_edition_pages.sql
commit;

-- 20260807_saga_item_role_sin_paralela
begin;
\ir migrations/20260807_saga_item_role_sin_paralela.sql
commit;

-- 20260808_secdef_search_path_pg_temp
begin;
\ir migrations/20260808_secdef_search_path_pg_temp.sql
commit;

-- 20260809_save_saga_route_valida_subarbol
begin;
\ir migrations/20260809_save_saga_route_valida_subarbol.sql
commit;

-- 20260810_club_event_validacion
begin;
\ir migrations/20260810_club_event_validacion.sql
commit;

-- 20260811_spawn_linked_activity_defaults
begin;
\ir migrations/20260811_spawn_linked_activity_defaults.sql
commit;

-- 20260814_club_round_history_weeks
begin;
\ir migrations/20260814_club_round_history_weeks.sql
commit;

-- 20260814_notes_public_select
begin;
\ir migrations/20260814_notes_public_select.sql
commit;

-- 20260815_genres_gin_indexes
begin;
\ir migrations/20260815_genres_gin_indexes.sql
commit;

-- 20260815_saga_placement_anclado
begin;
\ir migrations/20260815_saga_placement_anclado.sql
commit;

-- 20260816_grant_anon_read_block_helpers
begin;
\ir migrations/20260816_grant_anon_read_block_helpers.sql
commit;

-- 20260817_passes_planned_on
begin;
\ir migrations/20260817_passes_planned_on.sql
commit;

-- 20260818_catalog_a_shell_columns
begin;
\ir migrations/20260818_catalog_a_shell_columns.sql
commit;

-- 20260818_catalog_b_hydration_bypass
begin;
\ir migrations/20260818_catalog_b_hydration_bypass.sql
commit;

-- 20260818_catalog_c_hydrate_screen
begin;
\ir migrations/20260818_catalog_c_hydrate_screen.sql
commit;

-- 20260818_catalog_d_hydrate_book_flag
begin;
\ir migrations/20260818_catalog_d_hydrate_book_flag.sql
commit;

-- 20260818_catalog_e_register
begin;
\ir migrations/20260818_catalog_e_register.sql
commit;

-- 20260818_catalog_f_revoke_insert
begin;
\ir migrations/20260818_catalog_f_revoke_insert.sql
commit;

-- 20260818_grant_series_episode_runtime
begin;
\ir migrations/20260818_grant_series_episode_runtime.sql
commit;

-- 20260819_grant_passes_planned_on
begin;
\ir migrations/20260819_grant_passes_planned_on.sql
commit;

-- 20260820_comments_forbid_retarget
begin;
\ir migrations/20260820_comments_forbid_retarget.sql
commit;

-- 20260821_catalog_delete_guard_passes
begin;
\ir migrations/20260821_catalog_delete_guard_passes.sql
commit;

-- 20260822_club_event_following
begin;
\ir migrations/20260822_club_event_following.sql
commit;

-- 20260823_club_event_following_rpcs
begin;
\ir migrations/20260823_club_event_following_rpcs.sql
commit;

-- 20260823_people_credits_hydrated_at
begin;
\ir migrations/20260823_people_credits_hydrated_at.sql
commit;

-- 20260824_club_event_reminder_scheduler
begin;
\ir migrations/20260824_club_event_reminder_scheduler.sql
commit;

-- 20260825_notifications_system_actor
begin;
\ir migrations/20260825_notifications_system_actor.sql
commit;

-- 20260826_confirm_checkpoint_lee_passes
begin;
\ir migrations/20260826_confirm_checkpoint_lee_passes.sql
commit;

-- 20260827_hitos_autodeclarados
begin;
\ir migrations/20260827_hitos_autodeclarados.sql
commit;

-- 20260828_push_devices
begin;
\ir migrations/20260828_push_devices.sql
commit;

-- 20260829_notification_preferences
begin;
\ir migrations/20260829_notification_preferences.sql
commit;

-- 20260830_notifications_dedupe_key
begin;
\ir migrations/20260830_notifications_dedupe_key.sql
commit;

-- 20260831_club_activity_role_gate_first
begin;
\ir migrations/20260831_club_activity_role_gate_first.sql
commit;

-- 20260832_editions_in_use_rpc
begin;
\ir migrations/20260832_editions_in_use_rpc.sql
commit;

-- 20260833_pass_reviews_updated_at
begin;
\ir migrations/20260833_pass_reviews_updated_at.sql
commit;

-- 20260834_thoughts_enum_values
begin;
\ir migrations/20260834_thoughts_enum_values.sql
commit;

-- 20260835_thoughts
begin;
\ir migrations/20260835_thoughts.sql
commit;

-- 20260836_thoughts_delete_moderate
begin;
\ir migrations/20260836_thoughts_delete_moderate.sql
commit;

-- 20260837_reactions_kind_allow_palette
begin;
\ir migrations/20260837_reactions_kind_allow_palette.sql
commit;

-- 20260838_comments_threads_spoiler_pin_edit
begin;
\ir migrations/20260838_comments_threads_spoiler_pin_edit.sql
commit;

-- 20260839_pin_comment_owner_only
begin;
\ir migrations/20260839_pin_comment_owner_only.sql
commit;

-- 20260840_club_event_type_enum
begin;
\ir migrations/20260840_club_event_type_enum.sql
commit;

-- 20260841_club_event_type_column
begin;
\ir migrations/20260841_club_event_type_column.sql
commit;

-- 20260842_club_event_typed_rpcs
begin;
\ir migrations/20260842_club_event_typed_rpcs.sql
commit;

-- 20260843_posts_enum_values
begin;
\ir migrations/20260843_posts_enum_values.sql
commit;

-- 20260844_posts
begin;
\ir migrations/20260844_posts.sql
commit;

-- 20260845_post_preferences
begin;
\ir migrations/20260845_post_preferences.sql
commit;

-- 20260846_posts_backfill
begin;
\ir migrations/20260846_posts_backfill.sql
commit;

-- 20260847_posts_drop_thoughts
begin;
\ir migrations/20260847_posts_drop_thoughts.sql
commit;

-- 20260848_comment_target_anchor
begin;
\ir migrations/20260848_comment_target_anchor.sql
commit;

-- 20260849_notifications_dedupe_unique_index
begin;
\ir migrations/20260849_notifications_dedupe_unique_index.sql
commit;

-- 20260850_posts_select_moderate_authenticated_only
begin;
\ir migrations/20260850_posts_select_moderate_authenticated_only.sql
commit;

-- 20260851_related_posts_by_author
begin;
\ir migrations/20260851_related_posts_by_author.sql
commit;

-- 20260852_event_reminder_default_1w
begin;
\ir migrations/20260852_event_reminder_default_1w.sql
commit;

-- 20260853_activities_progress
begin;
\ir migrations/20260853_activities_progress.sql
commit;

-- 20260854_update_activity_details
begin;
\ir migrations/20260854_update_activity_details.sql
commit;

-- 20260855_unconfirm_checkpoint
begin;
\ir migrations/20260855_unconfirm_checkpoint.sql
commit;

-- 20260856_notification_type_followed_post_kinds
begin;
\ir migrations/20260856_notification_type_followed_post_kinds.sql
commit;

-- 20260857_follows_notify_events_post_categories
begin;
\ir migrations/20260857_follows_notify_events_post_categories.sql
commit;

-- 20260858_pass_dropped_reason
begin;
\ir migrations/20260858_pass_dropped_reason.sql
commit;

-- 20260859_people_aliases
begin;
\ir migrations/20260859_people_aliases.sql
commit;

-- 20260860_create_club_poll_returns_id
begin;
\ir migrations/20260860_create_club_poll_returns_id.sql
commit;

-- 20260861_fix_profiles_insert_role_escalation
begin;
\ir migrations/20260861_fix_profiles_insert_role_escalation.sql
commit;

-- 20260862_fix_pass_reviews_writes_revoke
begin;
\ir migrations/20260862_fix_pass_reviews_writes_revoke.sql
commit;

-- 20260863_profiles_role_insert_trigger
begin;
\ir migrations/20260863_profiles_role_insert_trigger.sql
commit;

-- 20260864_saga_tmdb_rpcs_service_role_only
begin;
\ir migrations/20260864_saga_tmdb_rpcs_service_role_only.sql
commit;

-- 20260865_catalog_size_columns_hardening
begin;
\ir migrations/20260865_catalog_size_columns_hardening.sql
commit;

-- 20260866_public_default_privileges_no_writes
begin;
\ir migrations/20260866_public_default_privileges_no_writes.sql
commit;

-- 20260867_catalog_delete_cascade_credits
begin;
\ir migrations/20260867_catalog_delete_cascade_credits.sql
commit;

-- 20260868_passes_state_dates_invariant
begin;
\ir migrations/20260868_passes_state_dates_invariant.sql
commit;

-- 20260869_secdef_search_path_pg_temp
begin;
\ir migrations/20260869_secdef_search_path_pg_temp.sql
commit;

-- 20260870_books_openlibrary_work_key_unique
begin;
\ir migrations/20260870_books_openlibrary_work_key_unique.sql
commit;

-- 20260871_hydrate_book_title_author
begin;
\ir migrations/20260871_hydrate_book_title_author.sql
commit;

-- 20260872_revoke_truncate_trigger_references
begin;
\ir migrations/20260872_revoke_truncate_trigger_references.sql
commit;

-- 20260873_passes_started_before_finished
begin;
\ir migrations/20260873_passes_started_before_finished.sql
commit;

-- 20260875_catalog_people_credits_episodes_readonly
begin;
\ir migrations/20260875_catalog_people_credits_episodes_readonly.sql
commit;

-- 20260876_drop_autoadd_library_entries
begin;
\ir migrations/20260876_drop_autoadd_library_entries.sql
commit;

-- 20260876_profiles_hide_dropped
begin;
\ir migrations/20260876_profiles_hide_dropped.sql
commit;

-- 20260876_reactions_emoji_libre
begin;
\ir migrations/20260876_reactions_emoji_libre.sql
commit;

-- 20260877_notifications_context
begin;
\ir migrations/20260877_notifications_context.sql
commit;

-- 20260878_catalog_technical_columns_gate
begin;
\ir migrations/20260878_catalog_technical_columns_gate.sql
commit;

-- 20260879_related_posts_by_author_sin_avances
begin;
\ir migrations/20260879_related_posts_by_author_sin_avances.sql
commit;

-- 20260880_manual_catalog_item
begin;
\ir migrations/20260880_manual_catalog_item.sql
commit;

-- 20260881_comments_voice_notes
begin;
\ir migrations/20260881_comments_voice_notes.sql
commit;

-- 20260882_repr_a_columns
begin;
\ir migrations/20260882_repr_a_columns.sql
commit;

-- 20260883_repr_b_hydrate_book_v3
begin;
\ir migrations/20260883_repr_b_hydrate_book_v3.sql
commit;

-- 20260884_repr_c_hydrate_hardening
begin;
\ir migrations/20260884_repr_c_hydrate_hardening.sql
commit;

-- 20260885_repr_d_curacion_alta_manual
begin;
\ir migrations/20260885_repr_d_curacion_alta_manual.sql
commit;

-- 20260886_repr_e_alta_gbonly
begin;
\ir migrations/20260886_repr_e_alta_gbonly.sql
commit;

-- 20260887_repr_f_merge_books_fn
begin;
\ir migrations/20260887_repr_f_merge_books_fn.sql
commit;

-- 20260888_repr_g_merge_books_completo
begin;
\ir migrations/20260888_repr_g_merge_books_completo.sql
commit;

-- 20260889_repr_h_merge_books_href
begin;
\ir migrations/20260889_repr_h_merge_books_href.sql
commit;

-- 20260890_repr_i_hydrate_books_bulk
begin;
\ir migrations/20260890_repr_i_hydrate_books_bulk.sql
commit;

-- 20260891_repr_j_bulk_uuid_guard
begin;
\ir migrations/20260891_repr_j_bulk_uuid_guard.sql
commit;

-- 20260892_widget_snapshot_two_level
begin;
\ir migrations/20260892_widget_snapshot_two_level.sql
commit;

-- 20260893_play_games
begin;
\ir migrations/20260893_play_games.sql
commit;

-- 20260894_play_players
begin;
\ir migrations/20260894_play_players.sql
commit;

-- 20260902_pet_state
begin;
\ir migrations/20260902_pet_state.sql
commit;

-- 20260903_pet_daily_missions
begin;
\ir migrations/20260903_pet_daily_missions.sql
commit;

-- 20260904_pet_achievement_tiers
begin;
\ir migrations/20260904_pet_achievement_tiers.sql
commit;

-- 20260905_get_companion_state
begin;
\ir migrations/20260905_get_companion_state.sql
commit;

-- 20260906_pet_nudges
begin;
\ir migrations/20260906_pet_nudges.sql
commit;

-- 20260907_pet_battles
begin;
\ir migrations/20260907_pet_battles.sql
commit;

-- 20260906170958_get_burrow_pets
begin;
\ir migrations/20260906170958_get_burrow_pets.sql
commit;
