// Generated by scripts/pet-pixellab/combat-manifest.mjs. Companion sheets are independent.
export type CombatAnimation = "idle" | "attack" | "hurt" | "ko" | "guard" | "charge" | "vulnerable";
export type CombatArtEntry = {src:string; hash:string; cell:number; width:number; height:number; anims:Partial<Record<CombatAnimation,{row:number;frames:number}>>};
export const COMBAT_ART: Readonly<Record<string,CombatArtEntry>> = {
  "adult/barbarian": {
    "src": "/pet/combat/adult/barbarian.png",
    "hash": "7fde52ca7b",
    "cell": 104,
    "width": 832,
    "height": 416,
    "anims": {
      "idle": {
        "row": 0,
        "frames": 8
      },
      "attack": {
        "row": 1,
        "frames": 8
      },
      "hurt": {
        "row": 2,
        "frames": 8
      },
      "ko": {
        "row": 3,
        "frames": 8
      }
    }
  },
  "adult/bard": {
    "src": "/pet/combat/adult/bard.png",
    "hash": "63ebf7050e",
    "cell": 104,
    "width": 832,
    "height": 416,
    "anims": {
      "idle": {
        "row": 0,
        "frames": 8
      },
      "attack": {
        "row": 1,
        "frames": 8
      },
      "hurt": {
        "row": 2,
        "frames": 8
      },
      "ko": {
        "row": 3,
        "frames": 8
      }
    }
  },
  "adult/cleric": {
    "src": "/pet/combat/adult/cleric.png",
    "hash": "6eb2581e91",
    "cell": 108,
    "width": 864,
    "height": 432,
    "anims": {
      "idle": {
        "row": 0,
        "frames": 8
      },
      "attack": {
        "row": 1,
        "frames": 8
      },
      "hurt": {
        "row": 2,
        "frames": 8
      },
      "ko": {
        "row": 3,
        "frames": 8
      }
    }
  },
  "adult/fighter": {
    "src": "/pet/combat/adult/fighter.png",
    "hash": "4c3c88c286",
    "cell": 104,
    "width": 832,
    "height": 416,
    "anims": {
      "idle": {
        "row": 0,
        "frames": 8
      },
      "attack": {
        "row": 1,
        "frames": 8
      },
      "hurt": {
        "row": 2,
        "frames": 8
      },
      "ko": {
        "row": 3,
        "frames": 8
      }
    }
  },
  "adult/ranger": {
    "src": "/pet/combat/adult/ranger.png",
    "hash": "83c3accd9f",
    "cell": 96,
    "width": 768,
    "height": 384,
    "anims": {
      "idle": {
        "row": 0,
        "frames": 8
      },
      "attack": {
        "row": 1,
        "frames": 8
      },
      "hurt": {
        "row": 2,
        "frames": 8
      },
      "ko": {
        "row": 3,
        "frames": 8
      }
    }
  },
  "adult/wizard": {
    "src": "/pet/combat/adult/wizard.png",
    "hash": "e50eb08052",
    "cell": 100,
    "width": 800,
    "height": 400,
    "anims": {
      "idle": {
        "row": 0,
        "frames": 8
      },
      "attack": {
        "row": 1,
        "frames": 8
      },
      "hurt": {
        "row": 2,
        "frames": 8
      },
      "ko": {
        "row": 3,
        "frames": 8
      }
    }
  },
  "enemy/brote": {
    "src": "/pet/combat/enemy/brote.png",
    "hash": "12a0df0ec2",
    "cell": 88,
    "width": 704,
    "height": 528,
    "anims": {
      "idle": {
        "row": 0,
        "frames": 8
      },
      "attack": {
        "row": 1,
        "frames": 8
      },
      "hurt": {
        "row": 2,
        "frames": 8
      },
      "ko": {
        "row": 3,
        "frames": 8
      },
      "guard": {
        "row": 4,
        "frames": 8
      },
      "charge": {
        "row": 5,
        "frames": 8
      }
    }
  },
  "enemy/caparazon": {
    "src": "/pet/combat/enemy/caparazon.png",
    "hash": "bbce9a8cf0",
    "cell": 92,
    "width": 736,
    "height": 552,
    "anims": {
      "idle": {
        "row": 0,
        "frames": 8
      },
      "attack": {
        "row": 1,
        "frames": 8
      },
      "hurt": {
        "row": 2,
        "frames": 8
      },
      "ko": {
        "row": 3,
        "frames": 8
      },
      "guard": {
        "row": 4,
        "frames": 8
      },
      "vulnerable": {
        "row": 5,
        "frames": 8
      }
    }
  },
  "veteran/barbarian": {
    "src": "/pet/combat/veteran/barbarian.png",
    "hash": "a74670cdeb",
    "cell": 112,
    "width": 896,
    "height": 448,
    "anims": {
      "idle": {
        "row": 0,
        "frames": 8
      },
      "attack": {
        "row": 1,
        "frames": 8
      },
      "hurt": {
        "row": 2,
        "frames": 8
      },
      "ko": {
        "row": 3,
        "frames": 8
      }
    }
  },
  "veteran/bard": {
    "src": "/pet/combat/veteran/bard.png",
    "hash": "da68a77f3e",
    "cell": 104,
    "width": 832,
    "height": 416,
    "anims": {
      "idle": {
        "row": 0,
        "frames": 8
      },
      "attack": {
        "row": 1,
        "frames": 8
      },
      "hurt": {
        "row": 2,
        "frames": 8
      },
      "ko": {
        "row": 3,
        "frames": 8
      }
    }
  },
  "veteran/cleric": {
    "src": "/pet/combat/veteran/cleric.png",
    "hash": "cd0155eb49",
    "cell": 92,
    "width": 736,
    "height": 368,
    "anims": {
      "idle": {
        "row": 0,
        "frames": 8
      },
      "attack": {
        "row": 1,
        "frames": 8
      },
      "hurt": {
        "row": 2,
        "frames": 8
      },
      "ko": {
        "row": 3,
        "frames": 8
      }
    }
  },
  "veteran/fighter": {
    "src": "/pet/combat/veteran/fighter.png",
    "hash": "f1fee259c1",
    "cell": 100,
    "width": 800,
    "height": 400,
    "anims": {
      "idle": {
        "row": 0,
        "frames": 8
      },
      "attack": {
        "row": 1,
        "frames": 8
      },
      "hurt": {
        "row": 2,
        "frames": 8
      },
      "ko": {
        "row": 3,
        "frames": 8
      }
    }
  },
  "veteran/ranger": {
    "src": "/pet/combat/veteran/ranger.png",
    "hash": "f1de80d150",
    "cell": 104,
    "width": 832,
    "height": 416,
    "anims": {
      "idle": {
        "row": 0,
        "frames": 8
      },
      "attack": {
        "row": 1,
        "frames": 8
      },
      "hurt": {
        "row": 2,
        "frames": 8
      },
      "ko": {
        "row": 3,
        "frames": 8
      }
    }
  },
  "veteran/wizard": {
    "src": "/pet/combat/veteran/wizard.png",
    "hash": "081137e8d3",
    "cell": 92,
    "width": 736,
    "height": 368,
    "anims": {
      "idle": {
        "row": 0,
        "frames": 8
      },
      "attack": {
        "row": 1,
        "frames": 8
      },
      "hurt": {
        "row": 2,
        "frames": 8
      },
      "ko": {
        "row": 3,
        "frames": 8
      }
    }
  },
  "young/barbarian": {
    "src": "/pet/combat/young/barbarian.png",
    "hash": "9c17c167a5",
    "cell": 92,
    "width": 736,
    "height": 368,
    "anims": {
      "idle": {
        "row": 0,
        "frames": 8
      },
      "attack": {
        "row": 1,
        "frames": 8
      },
      "hurt": {
        "row": 2,
        "frames": 8
      },
      "ko": {
        "row": 3,
        "frames": 8
      }
    }
  },
  "young/bard": {
    "src": "/pet/combat/young/bard.png",
    "hash": "7aceb95b69",
    "cell": 92,
    "width": 736,
    "height": 368,
    "anims": {
      "idle": {
        "row": 0,
        "frames": 8
      },
      "attack": {
        "row": 1,
        "frames": 8
      },
      "hurt": {
        "row": 2,
        "frames": 8
      },
      "ko": {
        "row": 3,
        "frames": 8
      }
    }
  },
  "young/cleric": {
    "src": "/pet/combat/young/cleric.png",
    "hash": "f41b890ad0",
    "cell": 96,
    "width": 768,
    "height": 384,
    "anims": {
      "idle": {
        "row": 0,
        "frames": 8
      },
      "attack": {
        "row": 1,
        "frames": 8
      },
      "hurt": {
        "row": 2,
        "frames": 8
      },
      "ko": {
        "row": 3,
        "frames": 8
      }
    }
  },
  "young/fighter": {
    "src": "/pet/combat/young/fighter.png",
    "hash": "11ad8b4b6a",
    "cell": 100,
    "width": 800,
    "height": 400,
    "anims": {
      "idle": {
        "row": 0,
        "frames": 8
      },
      "attack": {
        "row": 1,
        "frames": 8
      },
      "hurt": {
        "row": 2,
        "frames": 8
      },
      "ko": {
        "row": 3,
        "frames": 8
      }
    }
  },
  "young/ranger": {
    "src": "/pet/combat/young/ranger.png",
    "hash": "b0e4f74c92",
    "cell": 92,
    "width": 736,
    "height": 368,
    "anims": {
      "idle": {
        "row": 0,
        "frames": 8
      },
      "attack": {
        "row": 1,
        "frames": 8
      },
      "hurt": {
        "row": 2,
        "frames": 8
      },
      "ko": {
        "row": 3,
        "frames": 8
      }
    }
  },
  "young/wizard": {
    "src": "/pet/combat/young/wizard.png",
    "hash": "7f1826b2d2",
    "cell": 92,
    "width": 736,
    "height": 368,
    "anims": {
      "idle": {
        "row": 0,
        "frames": 8
      },
      "attack": {
        "row": 1,
        "frames": 8
      },
      "hurt": {
        "row": 2,
        "frames": 8
      },
      "ko": {
        "row": 3,
        "frames": 8
      }
    }
  }
};
