"use client";
import Image from "next/image";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {useTranslations} from "next-intl";
import {Button} from "@/components/ui/button";
import {ActionMenu} from "@/components/ui/action-menu";
import {SheetShell} from "@/components/saga/sheet-shell";
import {ChevronLeftIcon,ChevronRightIcon} from "@/components/ui/icons";
import {deletePhoto,setCoverPhoto,setPhotoSharing} from "@/lib/experiences/photo-actions";
import type {ExperienceDetail,ExperienceError,ExperiencePhoto,ExperienceResult} from "@/lib/experiences/types";
import {ExperiencePhotoUpload} from "./experience-photo-upload";
export function ExperienceGallery({experience:e}:{experience:ExperienceDetail}) {
  const t=useTranslations("experiences"),router=useRouter(),[deleting,setDeleting]=useState<ExperiencePhoto|null>(null),[viewingId,setViewingId]=useState<string|null>(null),[pending,start]=useTransition(),[error,setError]=useState<ExperienceError|null>(null);
  const viewing=e.photos.find(photo=>photo.id===viewingId),viewingIndex=e.photos.findIndex(photo=>photo.id===viewingId);
  function run(work:()=>Promise<ExperienceResult<unknown>>,done?:()=>void) {setError(null);start(async()=>{const result=await work();if(!result.ok) setError(result.error);else {done?.();router.refresh();}});}
  return <section id="experience-photos" className="space-y-4 scroll-mt-24"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-baseline gap-3"><h2 className="font-serif text-xl font-semibold">{t("gallery")}</h2>{e.photos.length>0&&<span className="text-xs text-muted-foreground">{t("album.photoCount",{count:e.photos.length})}</span>}</div>{e.canContribute&&<ExperiencePhotoUpload experienceId={e.id} moments={e.moments}/>}</div>
    {e.photos.length ? <div className={`grid items-start gap-3 ${e.photos.length===1 ? "max-w-xl grid-cols-1" : "grid-cols-2 sm:grid-cols-3"}`}>{e.photos.map((p,index)=><figure key={p.id} className={`min-w-0 rounded-cover border border-border bg-surface p-2 shadow-card ${e.photos.length>2&&index===0 ? "col-span-2 row-span-2" : ""}`}>
      <button type="button" aria-label={t("openPhoto")} className="block min-h-11 w-full overflow-hidden rounded-detail" onClick={()=>{setError(null);setViewingId(p.id);}}><Image src={`/api/experience-photos/${p.id}`} alt={t("photoAlt",{name:e.title})} width={1200} height={900} unoptimized className="aspect-[4/3] w-full object-cover"/></button>
      <figcaption className="flex flex-wrap items-center justify-between gap-1 px-1 pb-1 pt-3 text-xs text-muted-foreground"><span className="min-w-0 break-words">{p.momentId ? e.moments.find(m=>m.id===p.momentId)?.title : p.authorName ? t("photoAuthor",{name:p.authorName}) : t("generalGallery")}</span>{e.coverPhotoId===p.id&&<span className="font-medium text-foreground">{t("cover")}</span>}</figcaption>
    </figure>)}</div> : e.canContribute&&<div className="flex min-h-40 items-center gap-5 rounded-card border border-dashed border-border bg-surface/50 p-6"><svg aria-hidden viewBox="0 0 80 70" className="h-16 w-20 shrink-0 text-muted-foreground" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 8H62V51H12Z" transform="rotate(-8 37 29)"/><path d="M19 17H72V63H19Z" fill="var(--surface)"/><path d="M25 48L37 34L46 43L54 31L66 48"/><circle cx="32" cy="27" r="4"/></svg><div><p className="font-serif text-lg font-semibold">{t("album.photoEmptyTitle")}</p><p className="mt-2 max-w-sm text-sm text-muted-foreground">{t("album.photoEmptyHint")}</p></div></div>}
    {error&&!deleting&&!viewing&&<p role="alert" className="text-sm text-status-dropped">{t(`errors.${error}`)}</p>}
    {deleting&&<SheetShell title={t("deletePhoto")} onClose={()=>{setDeleting(null);setError(null);}}><div className="space-y-4"><Image src={`/api/experience-photos/${deleting.id}`} alt={t("photoAlt",{name:e.title})} width={800} height={600} unoptimized className="max-h-64 w-full rounded-cover object-contain"/><p>{t("deletePhotoConfirm")}</p>{error&&<p role="alert" className="text-sm text-status-dropped">{t(`errors.${error}`)}</p>}<Button variant="danger" className="min-h-11 w-full" disabled={pending} onClick={()=>run(()=>deletePhoto(deleting.id),()=>{setDeleting(null);setViewingId(null);})}>{t("deletePhoto")}</Button></div></SheetShell>}
    {viewing&&!deleting&&<SheetShell title={t("openPhoto")} onClose={()=>{setViewingId(null);setError(null);}}><div className="max-h-[80svh] space-y-4 overflow-y-auto">
      <Image src={`/api/experience-photos/${viewing.id}`} alt={t("photoAlt",{name:e.title})} width={1600} height={1200} unoptimized className="max-h-[48svh] w-full rounded-cover object-contain bg-surface-muted"/>
      <div className="flex items-center justify-between gap-3"><div className="min-w-0 space-y-1 text-xs text-muted-foreground">{viewing.authorName&&<p>{t("photoAuthor",{name:viewing.authorName})}</p>}{viewing.momentId&&<p>{e.moments.find(m=>m.id===viewing.momentId)?.title}</p>}{e.coverPhotoId===viewing.id&&<p className="font-medium text-foreground">{t("cover")}</p>}</div>
        {viewing.canManage&&<ActionMenu label={t("photoActions")} items={[e.canEdit&&viewing.isAuthor&&{key:"cover",label:e.coverPhotoId===viewing.id ? t("clearCover") : t("setCover"),disabled:pending,onSelect:()=>run(()=>setCoverPhoto(e.id,e.coverPhotoId===viewing.id ? null : viewing.id))},{key:"delete",label:t("deletePhoto"),danger:true,onSelect:()=>{setError(null);setDeleting(viewing);}}]}/>}
      </div>
      {e.photos.length>1&&<div className="flex items-center justify-between gap-3"><button type="button" aria-label={t("album.previousPhoto")} disabled={viewingIndex===0} className="grid min-h-11 min-w-11 place-items-center rounded-full border border-border disabled:opacity-40" onClick={()=>{setError(null);setViewingId(e.photos[viewingIndex-1].id);}}><ChevronLeftIcon aria-hidden className="h-5 w-5"/></button><p className="text-xs text-muted-foreground">{t("album.photoPosition",{index:viewingIndex+1,count:e.photos.length})}</p><button type="button" aria-label={t("album.nextPhoto")} disabled={viewingIndex===e.photos.length-1} className="grid min-h-11 min-w-11 place-items-center rounded-full border border-border disabled:opacity-40" onClick={()=>{setError(null);setViewingId(e.photos[viewingIndex+1].id);}}><ChevronRightIcon aria-hidden className="h-5 w-5"/></button></div>}
      {viewing.isAuthor&&<div className="border-t border-border pt-3"><label className="flex min-h-11 cursor-pointer items-center gap-3 text-sm"><input type="checkbox" checked={viewing.shareWithProfile} disabled={pending} onChange={event=>run(()=>setPhotoSharing(viewing.id,event.target.checked))} className="h-5 w-5 accent-accent"/>{t("sharePhoto")}</label><p className="mt-1 text-xs text-muted-foreground">{t("sharePhotoHint")}</p></div>}
      {error&&<p role="alert" className="text-sm text-status-dropped">{t(`errors.${error}`)}</p>}
    </div></SheetShell>}
  </section>;
}
