import type { FeedEvent } from "@/lib/social/feed";

// Evento de feed mínimo y válido para los tests de render de las tarjetas.
export function makeFeedEvent(over: Partial<FeedEvent> = {}): FeedEvent {
  return {
    id: "posts:p1",
    postId: "p1",
    kind: "started",
    actorId: "borja",
    actorUsername: "borja",
    actorDisplayName: "Borja",
    actorAvatarUrl: null,
    verb: "started",
    itemType: "series",
    itemId: "jojo",
    itemTitle: "JoJo's Bizarre Adventure",
    itemCoverUrl: null,
    itemSubtitle: null,
    itemYear: 2012,
    itemSeasons: 5,
    entryStatus: null,
    eventDate: new Date().toISOString(),
    orderDate: new Date().toISOString(),
    sortDate: new Date().toISOString(),
    rating: null,
    reviewExcerpt: null,
    reviewIsSpoiler: false,
    episode: null,
    reviewMeta: null,
    progress: null,
    thought: null,
    interactionTarget: { targetType: "post", targetId: "p1", interactionTargetId: "t1" },
    reactionCount: 0,
    viewerReacted: false,
    commentCount: 0,
    comments: [],
    reactions: {} as FeedEvent["reactions"],
    ...over,
  };
}
