import {beforeEach,expect,it,vi} from "vitest";
const h=vi.hoisted(()=>({getUser:vi.fn(),rpc:vi.fn(),upload:vi.fn(),remove:vi.fn(),invalidate:vi.fn()}));
vi.mock("server-only",()=>({}));
vi.mock("@/lib/supabase/server",()=>({createClient:async()=>({auth:{getUser:h.getUser},rpc:h.rpc})}));
vi.mock("@/lib/storage/experience-photos",()=>({uploadExperienceImage:h.upload,removeExperienceImage:h.remove}));
vi.mock("@/lib/reactivity/revalidate",()=>({revalidateExperiences:h.invalidate}));
import {uploadExperiencePhoto,setPhotoSharing,setCoverPhoto,deletePhoto} from "./photo-actions";
const root="67f23961-25ee-4d78-b7eb-d0faf895cf85",photo="67f23961-25ee-4d78-b7eb-d0faf895cf86",path=`${root}/${root}/${photo}.png`;
function form(size=100,mime="image/png",signature=true) {const bytes=new Uint8Array(size);if(signature)bytes.set([137,80,78,71,13,10,26,10]);const data=new FormData();data.set("photo",new File([bytes],"photo.png",{type:mime}));return data;}
beforeEach(()=>{vi.clearAllMocks();h.getUser.mockResolvedValue({data:{user:{id:root}}});h.rpc.mockImplementation(async(name:string)=>({data:name==="experience_reserve_photo" ? {id:photo,path} : {experienceId:root,path},error:null}));h.upload.mockResolvedValue(true);h.remove.mockResolvedValue(true);});
it("authenticates before any reservation or storage",async()=>{h.getUser.mockResolvedValue({data:{user:null}});expect(await uploadExperiencePhoto(root,null,form())).toEqual({ok:false,error:"unauthenticated"});expect(h.rpc).not.toHaveBeenCalled();expect(h.upload).not.toHaveBeenCalled();});
it("accepts exactly 2MiB with a valid signature and returns only an internal URL",async()=>{expect(await uploadExperiencePhoto(root,null,form(2*1024*1024))).toEqual({ok:true,data:{id:photo,url:`/api/experience-photos/${photo}`}});expect(h.upload).toHaveBeenCalledWith(path,expect.any(Blob),"image/png");expect(h.rpc).toHaveBeenCalledWith("experience_finish_photo",{p_photo_id:photo});expect(h.invalidate).toHaveBeenCalledWith(root);});
it("rejects oversized, spoofed MIME and wrong signature before reserving",async()=>{expect(await uploadExperiencePhoto(root,null,form(2*1024*1024+1))).toEqual({ok:false,error:"too_large"});expect(await uploadExperiencePhoto(root,null,form(100,"text/html"))).toEqual({ok:false,error:"unsupported_image"});expect(await uploadExperiencePhoto(root,null,form(100,"image/jpeg"))).toEqual({ok:false,error:"unsupported_image"});expect(await uploadExperiencePhoto(root,null,form(100,"image/png",false))).toEqual({ok:false,error:"unsupported_image"});expect(h.rpc).not.toHaveBeenCalled();});
it("compensates pending reservation after Storage failure",async()=>{h.upload.mockResolvedValue(false);expect((await uploadExperiencePhoto(root,null,form())).ok).toBe(false);expect(h.rpc).toHaveBeenCalledWith("experience_cancel_photo",{p_photo_id:photo});expect(h.remove).toHaveBeenCalledWith(path);expect(h.invalidate).not.toHaveBeenCalled();});
it("compensates uploaded bytes when membership is revoked before finish",async()=>{h.rpc.mockImplementation(async(name:string)=> name==="experience_finish_photo" ? {data:null,error:{code:"42501"}} : {data:{id:photo,path},error:null});expect(await uploadExperiencePhoto(root,null,form())).toEqual({ok:false,error:"forbidden"});expect(h.rpc).toHaveBeenCalledWith("experience_cancel_photo",{p_photo_id:photo});expect(h.remove).toHaveBeenCalledWith(path);});
it("does not upload after a forbidden reservation",async()=>{h.rpc.mockResolvedValue({data:null,error:{code:"42501"}});expect((await uploadExperiencePhoto(root,null,form())).ok).toBe(false);expect(h.upload).not.toHaveBeenCalled();});
it("shares and selects cover through authenticated RPC ownership",async()=>{await setPhotoSharing(photo,true);expect(h.rpc).toHaveBeenCalledWith("experience_set_photo_sharing",{p_photo_id:photo,p_enabled:true});await setCoverPhoto(root,photo);expect(h.rpc).toHaveBeenCalledWith("experience_set_cover",{p_id:root,p_photo_id:photo});});
it("does not delete bytes for another person's unauthorized photo",async()=>{h.rpc.mockResolvedValue({data:null,error:{code:"42501"}});expect(await deletePhoto(photo)).toEqual({ok:false,error:"forbidden"});expect(h.remove).not.toHaveBeenCalled();});
it("author deletion cleans Storage only after SQL removal",async()=>{expect((await deletePhoto(photo)).ok).toBe(true);expect(h.rpc).toHaveBeenCalledWith("experience_delete_photo",{p_photo_id:photo});expect(h.remove).toHaveBeenCalledWith(path);});
