import { execFileSync, spawnSync } from 'node:child_process';

// Only credentials generated by this checkout's disposable local instance.
const status = JSON.parse(execFileSync(process.env.SUPABASE_CLI ?? 'supabase',
  ['--workdir', '.superpowers/supabase-local', 'status', '--output', 'json'],
  { encoding: 'utf8', stdio: ['ignore', 'pipe', 'inherit'] }));
const url = new URL(status.API_URL);
if (!['127.0.0.1', 'localhost', '[::1]'].includes(url.hostname)) throw new Error('Local database required');
if (!status.ANON_KEY || !status.SERVICE_ROLE_KEY) throw new Error('Missing local keys');
const mode = process.argv[2];
const commands = {
  build: ['node_modules/next/dist/bin/next', 'build'],
  smoke: ['node_modules/@playwright/test/cli.js', 'test', '--config', 'playwright.ci.config.ts'],
};
if (!commands[mode]) throw new Error('Expected build or smoke');
const result = spawnSync(process.execPath, commands[mode], {
  stdio: 'inherit',
  env: { ...process.env,
    NEXT_PUBLIC_SUPABASE_URL: status.API_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: status.ANON_KEY,
    SUPABASE_SERVICE_ROLE_KEY: status.SERVICE_ROLE_KEY,
    PLAYWRIGHT_BASE_URL: 'http://127.0.0.1:3000',
  },
});
if (result.error) throw result.error;
process.exitCode = result.status ?? 1;
