import { execFileSync, spawnSync } from 'node:child_process';
import { mkdirSync, unlinkSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

// Only credentials generated by this checkout's disposable local instance.
const status = JSON.parse(execFileSync(process.env.SUPABASE_CLI ?? 'supabase',
  ['--workdir', '.superpowers/supabase-local', 'status', '--output', 'json'],
  { encoding: 'utf8', stdio: ['ignore', 'pipe', 'inherit'] }));
const url = new URL(status.API_URL);
if (!['127.0.0.1', 'localhost', '[::1]'].includes(url.hostname)) throw new Error('Local database required');
if (!status.ANON_KEY || !status.SERVICE_ROLE_KEY) throw new Error('Missing local keys');
const mode = process.argv[2];
const commands = {
  build: ['node_modules/next/dist/bin/next', 'build'],
  smoke: ['node_modules/@playwright/test/cli.js', 'test', '--config', 'playwright.ci.config.ts', ...process.argv.slice(3)],
  shop: ['node_modules/@playwright/test/cli.js', 'test', '--config', 'playwright.shop-local.config.ts', ...process.argv.slice(3)],
};
if (!commands[mode]) throw new Error('Expected build, smoke or shop');
const fixtureNamespace = String(Date.now());
// Shared, synthetic provider metadata; tests add their own UUID-scoped ISBNs.
const quotaFixturePath = resolve('.superpowers', `google-volume-quota-${fixtureNamespace}.ndjson`);
mkdirSync(resolve('.superpowers'), { recursive: true });
writeFileSync(quotaFixturePath, '');
const result = spawnSync(process.execPath, commands[mode], {
  // Server failures can leave the browser assertions green: late request APIs
  // during abandoned detail streams (#754) and import invalidation during a
  // render (#1250). Inspect the webServer output as well.
  stdio: mode !== 'build' ? ['inherit', 'pipe', 'pipe'] : 'inherit',
  encoding: 'utf8',
  maxBuffer: 10 * 1024 * 1024,
  env: { ...process.env,
    NEXT_PUBLIC_SUPABASE_URL: status.API_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: status.ANON_KEY,
    SUPABASE_SERVICE_ROLE_KEY: status.SERVICE_ROLE_KEY,
    PLAYWRIGHT_BASE_URL: 'http://127.0.0.1:3000',
    // Local fixtures shared by the test runner and its Next.js subprocess.
    CRON_SECRET: 'ci-letterboxd-fixture-only',
    // Next caches provider responses by request headers. A fresh synthetic
    // token keeps this run's one-shot failures independent of earlier runs.
    TMDB_API_KEY: `ci-letterboxd-fixture-only-${fixtureNamespace}`,
    DETAIL_NOTES_NAMESPACE: fixtureNamespace,
    GOOGLE_BOOKS_API_KEY: `ci-google-volume-fixture-only-${fixtureNamespace}`,
    GOOGLE_VOLUME_QUOTA_NAMESPACE: fixtureNamespace,
    GOOGLE_VOLUME_QUOTA_FIXTURES: quotaFixturePath,
    // Next.js forwards repeated --require values to its workers as one module
    // path. Load the fixture chain through a single entry point instead.
    NODE_OPTIONS: `${process.env.NODE_OPTIONS ?? ''} --require ./e2e/support/ci-providers.cjs`.trim(),
  },
});
unlinkSync(quotaFixturePath);
if (result.error) throw result.error;
if (mode !== 'build') {
  process.stdout.write(result.stdout ?? '');
  process.stderr.write(result.stderr ?? '');
  const output = `${result.stdout ?? ''}\n${result.stderr ?? ''}`;
  const lateRequestApi = /Route \/(?:libro|pelicula|serie)\/\[id\] used `(connection|cookies)\(\)` inside `after\(\)` while rendering/;
  const importInvalidationDuringRender = /Route \/importar used ["`]revalidate(?:Tag|Path)[^\r\n]*during render which is unsupported/;
  if (lateRequestApi.test(output)) {
    process.stderr.write('FAIL: a detail renderer read request data after its response closed (#754).\n');
    process.exitCode = 1;
  } else if (importInvalidationDuringRender.test(output)) {
    process.stderr.write('FAIL: an archive worker invalidated its cache during a render (#1250).\n');
    process.exitCode = 1;
  } else {
    process.exitCode = result.status ?? 1;
  }
} else {
  process.exitCode = result.status ?? 1;
}
